export const exercisesActionTypes = {
    FETCH_EXERCISES_STATRTS:'FETCH_EXERCISES_STATRTS',
    FETCH_EXERCISES_SUCCESS:'FETCH_EXERCISES_SUCCESS',
    FETCH_EXERCISES_FAILURE:'FETCH_EXERCISES_FAILURE'
}